### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-45#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig

**Comment by MorMundHS-MA** [comment]
JavaDoc in 3e809123e85a3489cab6e53fea7fa8d5b26c540f ergänzt.
